title: Specifications
repository: marrus-sh/Specifications
owner_name: kibigo!
owner_url: https://go.KIBI.family/
permalink: pretty
timezone: America/Los_Angeles
exclude:
- Makefile
- package.json
- package-lock.json
kramdown:
  toc_levels: 2..4
  gfm_quirks: no_auto_typographic
  smart_quotes: apos,apos,quot,quot
